#!/usr/bin/env bash

DIR="$HOME/.config/polybar/panels/menu"
uptime=$(uptime -p | sed -e 's/up //g')

theme="elementary_dark"

rofi_command="rofi -no-config -theme $SCRIPTPATH/powermenu.rasi"

# Options
shutdown="襤  Shutdown"
reboot="菱  Restart"
lock="  Lock"
suspend="鈴  Sleep"
logout="  Logout"

# Confirmation
confirm_exit() {
	rofi -dmenu\
        -no-config\
		-i\
		-no-fixed-num-lines\
		-p "Are You Sure? : "\
		-theme $DIR/$theme/confirm.rasi
}

# Message
msg() {
	rofi -no-config -theme "$DIR/$theme/message.rasi" -e "Available Options  -  yes / y / no / n"
}

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "Uptime: $uptime" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
			systemctl poweroff
			;;
    $reboot)
			systemctl reboot
      ;;
    $lock)
			i3lock
      ;;
    $suspend)
			mpc -q pause
			amixer set Master mute
			systemctl suspend
      ;;
    $logout) exec loginctl kill-session $XDG_SESSION_ID;;
esac