#!/usr/bin/env bash

DIR="$HOME/.config/polybar/panels/menu"

theme="elementary_dark"

rofi_command="rofi -no-config -theme $SCRIPTPATH/powermenu.rasi"

# Options
shutdown="襤  Shutdown"
reboot="菱  Restart"
lock="  Lock"
suspend="鈴  Sleep"
logout="  Logout"

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
			systemctl poweroff
			;;
    $reboot)
			systemctl reboot
      ;;
    $lock)
			i3lock
      ;;
    $suspend)
			mpc -q pause
			amixer set Master mute
			systemctl suspend
      ;;
    $logout) exec loginctl kill-session $XDG_SESSION_ID;;
esac