#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  # picom --config ~/.config/picom/picom.config &> /dev/null &
  picom --experimental-backends &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/wallpaper.jpg
fi

# Conky
# ~/.config/conky/start-conky.sh

rust-dwm-status

index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    monitor=$m width=$width polybar -q "main$index" -c $SCRIPTPATH/polybar.config &
    let index=index+1
  done
done
